client_id = "7640aaa57956d06daac541cdf69d93f3"
application_url = "https://cod-profit-app-production-efa1.up.railway.app"
embedded = true
name = "True COD Profit"

[access_scopes]
scopes = "read_orders,write_orders,read_products,read_fulfillments"

[auth]
redirect_urls = [
  "https://cod-profit-app-production-efa1.up.railway.app/auth/callback",
  "https://cod-profit-app-production-efa1.up.railway.app/auth/shopify/callback",
  "https://cod-profit-app-production-efa1.up.railway.app/api/auth/callback",
  "https://cod-profit-app-production-efa1.up.railway.app/api/auth"
]

[webhooks]
api_version = "2025-10"
  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"
  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks/orders/updated"
  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders/updated"
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"
  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[build]
automatically_update_urls_on_dev = true

[pos]
embedded = false